name: E2E Test

on:
  workflow_dispatch:
  pull_request:
      branches:
      - '*'
      - '!gh-pages'   # excludes gh-pages

jobs:
  e2e-test-run:
    name: Run on Chrome Latest
    runs-on: ubuntu-latest
    container:
      image:  cypress/browsers:latest
      options: --user 1001  # ← THIS IS THE IMPORTANT LINE!

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          start: |
            ls -al
            pnpm run dev
          wait-on: http://localhost:3000
        # continue-on-error: true

      # TODO: Create Report page
      # - name: Copy test execution videos
      #   run: |
      #     cp -r cypress/videos public/videos
      # - name: Merge test results into one
      #   run: pnpm run report:merge

      # - name: Generate HTML report
      #   run: pnpm run report:generate

      # - name: Deploy report page
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      #     user_name: 'github-actions[bot]'
      #     user_email: 'github-actions[bot]@users.noreply.github.com'
